FROM node:26-alpine AS build
WORKDIR /app
RUN apk add --no-cache python3 py3-pip ffmpeg
RUN pip install --break-system-packages --no-cache-dir -U yt-dlp yt-dlp-ejs
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build

FROM node:26-alpine
WORKDIR /app
RUN apk add --no-cache python3 py3-pip ffmpeg
RUN pip install --break-system-packages --no-cache-dir -U yt-dlp yt-dlp-ejs
COPY package*.json ./
RUN npm install --omit=dev
COPY --from=build /app/dist ./dist
EXPOSE 3000
CMD ["node", "dist/index.js"]
