services:
    backend:
        build:
            context: ./backend
            dockerfile: Dockerfile
        restart: unless-stopped
        env_file:
            - ./backend/.env
        depends_on:
            - db
        networks:
            - riptide
        volumes:
            - ./backend:/app
            - ./consume:/consume

    frontend:
        build:
            context: ./frontend
            dockerfile: Dockerfile
        restart: unless-stopped
        networks:
            - riptide
        volumes:
            - ./frontend:/app

    db:
        image: postgres:18-alpine
        restart: unless-stopped
        environment:
            POSTGRES_USER: riptide
            POSTGRES_PASSWORD: riptide
            POSTGRES_DB: riptide
        volumes:
            - postgres-data:/var/lib/postgresql
        networks:
            - riptide
        ports:
            - "5432:5432"

    nginx:
        image: nginx:1.30-alpine
        restart: unless-stopped
        depends_on:
            - backend
            - rustfs
            - frontend
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
        ports:
            - "5173:5173"
        networks:
            - riptide

    rustfs:
        image: rustfs/rustfs:latest
        restart: unless-stopped
        environment:
            RUSTFS_ACCESS_KEY: riptide
            RUSTFS_SECRET_KEY: riptide
            RUSTFS_CONSOLE_ENABLE: "true"
        volumes:
            - rustfs-data:/data
        networks:
            - riptide
        ports:
            - "9001:9001"

networks:
    riptide:

volumes:
    postgres-data:
    rustfs-data:
